name: Expo CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install Expo CLI
      run: npm install -g expo-cli

    - name: Install EAS CLI
      run: npm install -g eas-cli

    - name: Login to Expo
      run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

    - name: Login to EAS
      run: eas login --token ${{ secrets.EXPO_TOKEN }}

    - name: Build the app (Android)
      run: eas build --platform android --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Build the app (iOS)
      run: eas build --platform ios --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: expo-app
        path: dist/*

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: expo-app
        path: dist

    - name: Publish to Expo
      run: eas update --branch deployment_0602_branch --message "Update"
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
